### ISSUE TITLE
Broken for version v1.10.1

### ISSUE THREAD

**Issue by 2nOrderEDO** [christophenne/trello2planka#23]
Seems to be broken for v1.10.1 (latest at the time of posting). I can buy you 5 or 10 coffees as a donation to fix it :-)

**Comment by christophenne** [comment]
Thanks for letting me know, I'll look into it.

**Comment by christophenne** [comment]
There was a breaking change in the planka API, it's fixed now.

**Comment by 2nOrderEDO** [comment]
Great, will test it and report. How can I make a donation to you?

**Comment by christophenne** [comment]
Thanks, but no need to donate, I would have had to fix this anyway :)

**Comment by 2nOrderEDO** [comment]
Sorry, maybe I'm doing something wrong. I get this error:

```
> trello2planka@0.0.1 import-sample-board
> npm run import-board -- --file=sample-board-export.json


> trello2planka@0.0.1 import-board
> node src/index.js "--file=sample-board-export.json"

file:///home/enrique/Downloads/trello2planka-develop(1)/trello2planka-develop/src/utils/config.js:6
        if (err || !config?.planka?.api || !config?.planka?.importUser || !config?.planka?.importPassword) {
                           ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```
And this is my config file:

{
  "importOptions": {
    "createdProjectName": "TEST",
    "fetchAttachments": false
  },
  "planka": {
    "api": "https://kanban.censored.ch/api/", 
    "importUser": "user (censored)",
    "importPassword": "censored"
  },
  "trello": {
    "api": "https://api.trello.com/1/",
    "apiKey": "blabla",
    "apiToken": "blablabla"
  }
}

Maybe I'm just a n00b hehe

**Comment by christophenne** [comment]
Most likely related to the node version. Which are you running? Execute `node -v` in the command line please. 

I'm using v18, if you have some older version, maybe try to install v18 as well. I am using the nvm tool to manage multiple node versions on my machine: https://github.com/nvm-sh/nvm .

**Comment by 2nOrderEDO** [comment]
npm -v:
8.5.1
node -v:
v12.22.9

**Comment by 2nOrderEDO** [comment]
Ok, I installed nvm and updated node an now it works with the example board. Thanks for the help, I never used node before :-)

**Comment by christophenne** [comment]
Nice to hear, happy to help :)
