### ISSUE TITLE
Code references Planka end points which dont exist

### ISSUE THREAD

**Issue by zezretro** [christophenne/trello2planka#28]
I have gotten to this error when running

npm run import-sample-board

> authenticated POST to https://--server--/api/projects/979344937311011849/boards
> Error: authenticated POST failed, status code = 404, code = E_NOT_FOUND, problems = undefined

I looked up the endpoints in paths.js and I tried to manually hit them on my planka instance. I was able to make it work by extracting a auth token and using curl to include it in another request.

I found that only some of them worked and the pattern was:

cards/979345007557215244
works and returns data on that card but

cards/979345007557215244/labels
does not work.

The secondary layer calls never work. 

Is this some issue which can be fixed in trello2planka or have these parts of the planka API not been finished yet?

thank you

**Comment by christophenne** [comment]
hi, which planka version are you running? because it's possible that it's not compatible anymore.

**Comment by zezretro** [comment]
Hiya, I am using Version 1.10.3 of planka.

Is there is a last known working version of planka? maybe I can do a one time import using that older version and then upgrade back to the latest

**Comment by christophenne** [comment]
The last known version it works with is 1.10.1, I have not tested the newer versions yet.

> maybe I can do a one time import using that older version and then upgrade back to the latest

If that's possible for you, you could give that a try. Alternatively you could use the import feature on the planka UI directly, it's based on trello2planka but you can't import attachments or archived items (for more details see the README https://github.com/christophenne/trello2planka/blob/develop/README.md). 

Nevertheless I will test with the latest planka version soon and try to support it too, but I can't make any promises.

**Comment by christophenne** [comment]
I just tested the sample import with planka 1.11.0, and it works fine. Maybe directly try this version instead of downgrading and upgrading afterwards.

**Comment by zezretro** [comment]
Thank you, I will try this and report back

**Comment by zezretro** [comment]
I have been testing my setup. There is an [issue](https://github.com/plankanban/planka/issues/418) with the version number so I am 99% sure I am on 1.11.0.

This is the error I get now

> node src/index.js --file=sample-board-export.json

authenticated GET to https://p.zezwork.com/api/users/me
status =  200
authenticated POST to https://p.zezwork.com/api/projects/979344937311011849/boards
Error: authenticated POST failed, status code = 404, code = E_NOT_FOUND, problems = undefined
    at authenticatedPost (file:///home/pi/trello2planka/src/planka/client.js:71:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createBoard (file:///home/pi/trello2planka/src/planka/client.js:46:45)
    at async getPlankaProjectAndBoard (file:///home/pi/trello2planka/src/planka/import.js:31:25)
    at async importTrelloBoard (file:///home/pi/trello2planka/src/planka/import.js:15:29)
    at async main (file:///home/pi/trello2planka/src/index.js:8:9)

**Comment by christophenne** [comment]
Since the first call after the GET /users/me is the POST boards call, I assume your config contains `"existingProjectId": "979344937311011849"`, right? 
Does this project actually exist ? - i.e. does this project appear on the web application and can you open it? If not, I imagine this would be the cause of the 404. Please make sure you are trying with the same user - if the user you use in trello2planka has no access to the project, this could also be the cause of the 404.

If this was not the cause of the problem, maybe we can find more details in the planka server log.

**Comment by zezretro** [comment]
Yes, thank you!

I had set existingProjectId and createdProjectName

I removed existingProjectId and the sample board has imported correctly. 

Thank you for your patience

**Comment by zezretro** [comment]
Also I found out that my Trello "Power Up" API permissions did not include attachments by default. I had to turn that on for the script to properly import images. It now is working for me, thank you again for your assistance.

**Comment by christophenne** [comment]
Great, happy to help.
